spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/realproject
    username: postgres
    password: jafar
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  messages:
    always-use-message-format: true
server:
  port: 8080