spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=task_manager
    username: postgres
    password: akhrullo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  messages:
    always-use-message-format: true
server:
  port: 8090